export * from "./welcome/welcome-screen"
export * from "./demo/demo-screen"
export * from "./demo/demo-list-screen"
// export other screens here
export * from "./home/home-screen"
export * from "./category/category-screen"
export * from "./amount/amount-screen"
export * from "./score/score-screen"
export * from "./profile/profile-screen"
export * from "./score-card/score-card-screen"
export * from "./main/main-screen"
export * from "./solution/solution-screen"
export * from "./instruction/instruction-screen"
export * from "./login/login-screen"
